version: '3'

services:
  postgres-local:
    container_name: adminjs_prisma
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superadmin
      PGDATA: /data/postgres
    ports:
      - '5432:5432'

volumes:
  data:
