version: '3.8'

name: adminjs-prisma

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - '5438:5432'

  mongo: # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: example
    ports:
      - '27017:27017'
